### ISSUE TITLE
Cannot open any file

### ISSUE THREAD

**Issue by MattBDev** [kenzierocks/MCPIDE#4]
When I try to open any file I keep getting an IndexOutOfBoundsException. [This link has two stacktraces I get for two different files I tried opening. ](http://haste.athion.net/ifawamidiz.pl)
I am using Java 12 from Oracle, javafx-sdk-12.0.2, and Windows 10 1903.

**Comment by kenzierocks** [comment]
After (finally) getting the program working in Windows, I can replicate. I'm surprised that this is giving wildly different results from Linux.
